version: "3.8"

services:
  ibm_mq_santi_data:
    container_name: my_ibm_mq_santi_data
    build: ./mq/
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=MY_QMGR_DEV # Queue Manager name
      - MQ_APP_PASSWORD=passw0rd # Password for the app-user
      - MQ_ENABLE_METRICS=true # To enable Prometheus metrics (port 9157)
    ports:
      - "1414:1414"
      - "9443:9443"
      - "9157:9157" # Prometheus port (only when metrics are enabled)
    # volumes:
    # - docker_pirate_ibm_mq_vol:/mnt/mqm
    networks:
      - docker_pirate_net
    deploy:
      resources:
        limits:
          memory: 2G
  app_santi:
    container_name: my_app_santi
    build: ./app/
    environment:
      # Environment variables to authenticate to Java app for connecting to MQ
      - APP_USER=app
      - APP_PASSWORD=passw0rd
    depends_on:
      - ibm_mq_santi_data
    networks:
      - docker_pirate_net
    deploy:
      resources:
        limits:
          memory: 2G

# volumes:
#   docker_pirate_ibm_mq_vol:
#     name: docker_pirate_ibm_mq_vol

networks:
  docker_pirate_net:
    driver: bridge
    name: docker_pirate_net
